# Generated by Django 5.2.1 on 2025-05-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0002_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('groceries', 'Groceries'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=100),
        ),
    ]
