# Generated by Django 5.2.1 on 2025-05-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='total_budget',
            field=models.IntegerField(max_length=10),
        ),
    ]
