# Generated by Django 5.2.1 on 2025-05-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanagement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
